Features/refactor
mateuszorman/selenium_szkolenie pull request #4
Opened 2021-03-22 11:29 UTC by mateuszorman

2021-03-22 11:30 UTC, mateuszorman commented
Please take a look at my comments. Thanks!

2021-03-23 11:00 UTC, brozmus requested changes

2021-03-23 11:00 UTC, brozmus commented on szkolenie/szkolenie/Lesson1.cs
>          [Test]
Having [TestCase] you don't need [Test]. It's redundant now.

2021-03-23 11:00 UTC, brozmus commented on szkolenie/szkolenie/Lesson1.cs
>          [Test]
Having [TestCase] you don't need [Test]. It's redundant now.

2021-03-23 11:00 UTC, brozmus commented on szkolenie/szkolenie/Lesson2.cs
>          [Test]
Having [TestCase] you don't need [Test]. It's redundant now.

2021-03-23 11:00 UTC, brozmus commented on szkolenie/szkolenie/Lesson2.cs
> +            // assert
emtpy section?

2021-03-23 11:00 UTC, brozmus commented on szkolenie/szkolenie/Lesson3.cs
> +            // arrange
empty section?
You can put here assignment of popup.

2021-03-23 11:00 UTC, brozmus commented on szkolenie/szkolenie/Lesson3.cs
> +            var Popup = driver.FindElement(By.Id("at-cv-lightbox-close"));
local variables in camel case

2021-03-23 11:00 UTC, brozmus commented on szkolenie/szkolenie/Lesson3.cs
> +                // How to log.info?
Maybe Assert.Fail(message)?

2021-03-23 11:00 UTC, brozmus commented on szkolenie/szkolenie/Lesson3.cs
> +            // act
Add new line before this comment.

2021-03-23 14:04 UTC, mateuszorman commented on szkolenie/szkolenie/Lesson3.cs
> +                // How to log.info?
I want to put log just for information that popup is not visible anymore.

2021-03-25 13:03 UTC, brozmus approved these changes

2021-03-25 13:43 UTC, merged